### ISSUE TITLE
Initial Objective

### ISSUE THREAD

**Issue by fyhao** [fyhao/react-native-wf#1]
Refer https://github.com/fyhao/tns-webform-client/blob/master/app/lib/modBrowser/modWebform.js to implement basic webform protocol master detail navigations.

Objective:
------
- [ ] ios CI Setup https://github.com/fyhao/react-native-wf/issues/2
- [ ] android CI Setup https://github.com/fyhao/react-native-wf/issues/3
- [ ] Unit Test Setup https://github.com/fyhao/react-native-wf/issues/4
- [ ] Independent IPA Deployment https://github.com/fyhao/react-native-wf/issues/6
- [ ] Independent APK Deployment https://github.com/fyhao/react-native-wf/issues/7
- [ ] Basic Webform Protocol Master Detail Navigations https://github.com/fyhao/react-native-wf/issues/5
- [ ] Cloud Mac Setup https://github.com/fyhao/react-native-wf/issues/9
- [ ] Create github release, tag, in master branch, to mark the task completion

Once completed, this can be a reference for other react-native types of projects. 

This project is not going to replace tns-webform-client. Just for my learning towards react-native.
